### ISSUE TITLE
mind setting up a save system?

### ISSUE THREAD

**Issue by TimothyHill46** [bokub/vanity-eth#60] opened 2024-02-02 19:34 UTC
pretty much where the program can pause and save its place so that it does not have to recheck those addresses and when your ready to start it again, you just load up the save file and continue trying to get the ideal address you want.

**Comment by bokub** [comment] 2024-02-02 21:13
That's not how it works, there is not "progression" or "beginning", it's just pure randomness.

To illustrate, finding an address is like throwing 3 dice again and again until they all show a 6 at the same time. You can throw hundred of times without success, and the day after you succeed on the first try

Hope it's clear enough
Have a good day 

P.S: duplicate of #7

**Closed as completed** 2024-02-03 04:49 UTC
